services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: plant-your-day-dev
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sleep infinity
    ports:
      - "8000:8000"
